### ISSUE TITLE
Reporter doesn't get stats from registered metrics

### ISSUE THREAD

**Issue by schell** [sevco/metrics-datadog-exporter-rs#19]
Hi, first off - thanks for writing this crate. It has been very easy to integrate. Now, recently I stopped receiving metrics from my app and I assume this happened during the switch from `metrics = 0.17` to `metrics = 0.18`. It seems there is a mismatch between the `DataDogExporter` and the `Registry` that the `register_...` macros add to? This is a guess because I haven't identified the problem yet. It could also be that I don't understand how to properly use `metrics`. Here is a minimal test case: 

```rust
#[cfg(test)]
mod test {
    #[tokio::test]
    async fn ddog_stats_work() {
        let reporter = metrics_datadog_exporter::DataDogBuilder::default()
            .tags(vec![("test_tag_key".into(), "test_tag_value".into())])
            .write_to_stdout(true)
            .write_to_api(false, None)
            .build()
            .install()
            .unwrap();

        let counter: metrics::Counter = metrics::register_counter!("ddog_stats_work.counter");
        counter.increment(1);
        counter.increment(1);
        counter.increment(1);

        let gauge: metrics::Gauge = metrics::register_gauge!("ddog_stats_work.gauge");
        gauge.increment(2.5);
        gauge.increment(2.5);
        gauge.decrement(4.0);

        let stats = reporter.collect();
        assert_eq!(stats.len(), 2);
    }

}
```
Output: 
```
running 1 test
thread 'metrics::test::ddog_stats_work' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`'
```

**Comment by schell** [comment]
Looks like I was on `metrics-datadog-exporter = 0.1.7` and updating to `0.1.10` fixed the issue.

**Comment by aig787** [comment]
Yeah, we ran into the same, which is what https://github.com/sevco/metrics-datadog-exporter-rs/commit/9935fff267796adf43b4904e2be16b81bfd32962 was meant to address. With the `metrics` crate reexported from here you can be sure you don't get these version mismatching leading to missing metrics.
